### ISSUE TITLE
Use Hash.new({}) for category_settings

### ISSUE THREAD

**Issue by jonhue** [jonhue/notifications-rails#38]
This means refactoring `notifications-rails/notification-settings/lib/notification_settings/notification_library.rb` to expect `notification_setting.category_settings[x]` to resolve to something other than `nil`.

Follow up to #35

**Comment by TylerRick** [comment]
I wonder if a serializer like mentioned in #41 would be a good solution for this?

Maybe something like this?
```
class HashWithIndifferentAccessSerializer
  def self.dump(hash)
    # something
  end

  def self.load(hash)
    Hash.new({}.with_indifferent_access).
      merge(hash || {}).
      with_indifferent_access
  end
end
```

Or maybe we should be more structured than that... As in, make it a hash of "settings" (of some new Settings class/struct, like in https://github.com/jonhue/notifications-rails/issues/41#issuecomment-451022739... even if just a simple Struct) instead of a hash of unstructured hashes...

Would that work, or does it _need_ to be unstructured to allow pushers to be configured that are only registered and known about at run time?

**Comment by jonhue** [comment]
You're right. We don't know what pushers will be used in advance. But I really like the idea of doing this in a more structured manner!

So here is my take on this:
Instead of passing the type name to `define_pusher`, you'd have to pass the type directly. This would even make this code (https://github.com/jonhue/notifications-rails/blob/master/notification-pusher/lib/notification_pusher/pusher.rb#L16) a little easier on the eyes.

In my opinion structs make the most sense in this case. We could even preserve the current syntax almost entirely (assuming we wanted) and just allow the categories & pushers to be passed explicitly. I'm thinking something along the lines of this:

```ruby
Settings = Struct.new(:root_node) do
  def enabled?(pusher: nil, category: nil)
    root_node.enabled?(pusher: pusher, category: category)
  end
end

SettingNode = Struct.new(:value, :child_nodes, :type, :name) do
  def enabled?(pusher:, category:)
    return value if child_nodes.nil?
    return value if type == :pusher && pusher == name
    return value if type == :category && category == name

    child_nodes.each { |child_node| child_node.enabled?(pusher: pusher, category: category) }
  end
end
```
Obviously we may also do this using classes. (My naming decisions could also be improved.) This would then eliminate the need for using two columns to store this information. But we still need to define a way to serialize this data - preferably in a way that is easy to update.

**Comment by TylerRick** [comment]
I think a Struct is just a shorthand way to create a simple class, so you could easily convert to a "real" class and add `def initialize` later if needed... :)

I thought about suggesting combining those two columns into a single column but couldn't think of a concrete proposal for how to do that, so I'm glad to hear you're considering that as part of future plans...

I like your idea of using a tree and just asking child nodes if they are enabled. Not quite sure how you'd serialize it either, but I like how you're thinking of a good structure and API first, and hopefully it won't be too hard to serialize...

I probably won't have time to contribute much more for a while but I'm excited to see this evolve...

**Comment by TylerRick** [comment]
Another option I ran across recently that makes nested hashes nicer to deal with would be to wrap the hash in a [`Hashie::Mash`](https://github.com/intridea/hashie#how-does-the-wrapping-of-mash-sub-hashes-work).

But if you're already headed towards an even more structured solution (structs/classes instead of hashes), then I would probably continue in that direction... :)
